src/WebUI/Models/ContatoViewModel.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class ContatoViewModel
    {
        public List<TelefoneViewModel> ListTelefoneViewModel{get;} = new List<TelefoneViewModel>();
        
        public int Id {get; set;}

        [Required(ErrorMessage = "O 'Nome' deve ser preenchido")]
        [MinLength(3, ErrorMessage = "O 'Nome' deve ter no minimo 3 caracteres")]
        [MaxLength(100, ErrorMessage = "O 'Nome' deve ter no máximo 100 caracteres")]
        [DisplayName("Nome")]
        public string Nome {get; set;}

        [Required(ErrorMessage = "O 'Sobrenome' deve ser preenchido")]
        [MinLength(2, ErrorMessage = "O 'Sobrenome' deve ter no minimo 2 caracteres")]
        [MaxLength(100, ErrorMessage = "O 'Sobrenome' deve ter no máximo 100 caracteres")]
        [DisplayName("Sobrenome")]
        public string Sobrenome {get; set;}

        [Required(ErrorMessage = "O 'Email' deve ser preenchido")]   
        [MinLength(10, ErrorMessage = "O 'Email' deve ter no minimo 10 caracteres")]    
        [MaxLength(100, ErrorMessage = "O 'Email' deve ter no máximo 100 caracteres")]
        [EmailAddress(ErrorMessage = "Coloque um 'Email' válido")]
        [DisplayName("Email")]
        public string Email {get; set;}
    }
}

src/WebUI/Controllers/ContatoController.cs
using System.Collections.Generic;
using AutoMapper;
using DAO;
using DTO;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class ContatoController : Controller
    {

        private IContatoDAO _contatoDAO;
        private IMapper _mapper;
        private ITelefoneDAO _telefoneDAO;

        public ContatoController(IContatoDAO contatoDAO, IMapper mapper, ITelefoneDAO telefoneDAO){
            _contatoDAO = contatoDAO;
            _mapper = mapper;
            _telefoneDAO = telefoneDAO;
        }

        public IActionResult Details(int id){

            var contatoDTO = _contatoDAO.Consultar(id);
            var contatoViewModel = _mapper.Map<ContatoViewModel>(contatoDTO);
            var listTelefoneDTO = _telefoneDAO.ConsultarPorContato(id);
            
            foreach (var telefoneDTO in listTelefoneDTO)
                contatoViewModel.ListTelefoneViewModel.Add(_mapper.Map<TelefoneViewModel>(telefoneDTO));

            return View(contatoViewModel);
        }

        public IActionResult Index(){

            ViewData["Title"] = "Contato";
            ViewData["variavel"] = "teste";

            var contatoDTO = _contatoDAO.Consultar();
            var listContato = new List<ContatoViewModel>();

            foreach (var contato in contatoDTO)
                listContato.Add(_mapper.Map<ContatoViewModel>(contato));

            return View(listContato);
        }

        public IActionResult Create(){

            ViewData["Title"] = "Novo Contato";

            return View();
        }

        [HttpPost]
        public IActionResult Create(ContatoViewModel contatoViewModel)
        {
            if(!ModelState.IsValid) return View();

            var contatoDTO = _mapper.Map<ContatoDTO>(contatoViewModel);
            
            try
            {
                _contatoDAO.Criar(contatoDTO);
                TempData[Constants.Message.SUCCESS] = "Contato criado com sucesso";
            }
            catch (System.Exception e)
            {
                TempData[Constants.Message.ERROR] = e.Message;
            }
            

            return RedirectToAction("Index");
        }

        public IActionResult Update(int Id){
 
            ViewData["Title"] = "Atualizar Contato";

            var contatoDTO = _contatoDAO.Consultar(Id);

            var contato = _mapper.Map<ContatoViewModel>(contatoDTO);

            return View(contato);
        }

        [HttpPost]
        public IActionResult Update(ContatoViewModel contatoViewModel)
        {

            if(!ModelState.IsValid) return View();

            var contatoDTO = _mapper.Map<ContatoDTO>(contatoViewModel);

            try
            {
                _contatoDAO.Atualizar(contatoDTO);
                TempData[Constants.Message.SUCCESS] = "Contato (" + contatoViewModel.Nome + ") atualizado com sucesso!";
            }
            catch (System.Exception e)
            {
                TempData[Constants.Message.ERROR] = "Não foi possível atualizar o contato (" + contatoViewModel.Nome + "). Erro: " + e.Message;
            }
            

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int Id){
            _contatoDAO.Excluir(Id);
            return RedirectToAction("Index");
        }
    }
}

src/WebUI/Controllers/TelefoneController.cs
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using DAO;
using DTO;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class TelefoneController : Controller
    {
        private readonly ITelefoneDAO _telefoneDAO;
        private readonly IMapper _mapper;

        public TelefoneController(ITelefoneDAO telefoneDAO, IMapper mapper){
            _telefoneDAO = telefoneDAO;
            _mapper = mapper;
        }

        public ActionResult Create( int id){
            var telefoneViewModel = new TelefoneViewModel(){ ContatoId = id };
            return View(telefoneViewModel);
        }

        [HttpPost]
        public ActionResult Create(TelefoneViewModel telefoneViewModel){
            var telefoneDTO = _mapper.Map<TelefoneDTO>(telefoneViewModel);
            _telefoneDAO.Criar(telefoneDTO);
            return RedirectToAction("Details", "Contato", new {id = telefoneViewModel.ContatoId});
        }

        public ActionResult Delete(int contatoId, int id){
            _telefoneDAO.Excluir(id);
            return RedirectToAction("Details", "Contato", new {id = contatoId});
        }

        public ActionResult Update(int id){
            var telefoneDTO = _telefoneDAO.Consultar(id);
            var telefoneViewModel = _mapper.Map<TelefoneViewModel>(telefoneDTO);

            return View(telefoneViewModel);
        }

        [HttpPost]
        public ActionResult Update(TelefoneViewModel telefoneViewModel){
            if(!ModelState.IsValid) return View();
            var telefoneDTO = _mapper.Map<TelefoneDTO>(telefoneViewModel);
            _telefoneDAO.Atualizar(telefoneDTO);

            return RedirectToAction("Details", "Contato", new {id = telefoneViewModel.ContatoId});
        }
    }
}

src/WebUI/Views/Contato/Create.cshtml
@model WebUI.Models.ContatoViewModel;

<partial name="~/Views/Shared/_MessageSuccessErrorPartial.cshtml"/>

<form asp-action="Create">
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Nome">@Html.DisplayNameFor(model => model.Nome)</label>
            <input asp-for="Nome" class="form-control">
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Sobrenome">@Html.DisplayNameFor(model => model.Sobrenome)</label>
            <input asp-for="Sobrenome" class="form-control">
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Email">@Html.DisplayNameFor(model => model.Email)</label>
            <input asp-for="Email" class="form-control" value="">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <input type="submit" value="Submeter" class="btn btn-primary">
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
}

src/WebUI/Views/Contato/Details.cshtml
@model WebUI.Models.ContatoViewModel;

<form>
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Nome">@Html.DisplayNameFor(model => model.Nome)</label>
            <input asp-for="Nome" class="form-control" readonly>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Sobrenome">@Html.DisplayNameFor(model => model.Sobrenome)</label>
            <input asp-for="Sobrenome" class="form-control" readonly>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Email">@Html.DisplayNameFor(model => model.Email)</label>
            <input asp-for="Email" class="form-control" readonly>
        </div>
    </div>
</form>
<div style="text-align:right ;">
    <a class="btn btn-primary" asp-controller="Telefone" asp-action="Create" asp-route-id="@Model.Id">Novo Telefone</a>
    <a class="btn btn-primary" asp-controller="Contato" asp-action="Index" asp-route-id="@Model.Id">Voltar</a>
</div>

<table class="table" style="margin-top: 20px;">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ListTelefoneViewModel[0].Numero)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var telefone in Model.ListTelefoneViewModel)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => telefone.Numero)</td>
                <td>           
                    <a class="btn btn-info btn-sm" asp-controller="Telefone" asp-action="Update" asp-route-id="@telefone.Id">Atualizar</a>
                    <a class="btn btn-danger btn-sm" asp-controller="Telefone" asp-action="Delete" asp-route-contatoId="@Model.Id" asp-route-id="@telefone.Id">Excluir</a>
         
                </td>
            </tr>
        }

    </tbody>
</table>

src/WebUI/Views/Contato/Index.cshtml
@model IEnumerable<WebUI.Models.ContatoViewModel>;

<partial name="~/Views/Shared/_MessageSuccessErrorPartial.cshtml"/>

<a asp-controller="Contato" asp-action="Create" class="btn btn-primary">Adicionar</a>
    <table class="table" style="margin-top: 10px;">
        <thead>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sobrenome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a asp-controller="Contato" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                        <a asp-controller="Contato" asp-action="Update" asp-route-id="@item.Id">Atualizar</a>
                        <a asp-controller="Contato" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

src/WebUI/Views/Contato/Update.cshtml
@model WebUI.Models.ContatoViewModel;

<partial name="~/Views/Shared/_MessageSuccessErrorPartial.cshtml"/>

<form asp-action="Update">
    <input asp-for="Id" type="hidden">
    <div class="row">
        <div class="form-group col-md-4">
            <label asp-for="Nome">@Html.DisplayNameFor(model => model.Nome)</label>
            <input asp-for="Nome" class="form-control">
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Sobrenome">@Html.DisplayNameFor(model => model.Sobrenome)</label>
            <input asp-for="Sobrenome" class="form-control">
            <span asp-validation-for="Sobrenome" class="text-danger"></span>
        </div>
        <div class="form-group col-md-4">
            <label asp-for="Email">@Html.DisplayNameFor(model => model.Email)</label>
            <input asp-for="Email" class="form-control">
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <input type="submit" value="Submeter" class="btn btn-primary">
</form>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_validationScriptsPartial");
    }
}